name: SonarCloud

on:
  push:
    branches:
      - dev
      - hotfix
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Run SonarCloud
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Run test coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Run test json
        run: go test -json ./... > report.json

      - name: Run Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
